#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json
blacklist = ["scratch"]

[[wildcard]]
pattern = "~/code/hobby/*"
startup_command = "tdl"

[[wildcard]]
pattern = "~/code/work/git/*"
startup_command = "tdl"

[[session]]
name = "azure-devops"
path = "~/Work/azure-devops"
startup_command = "tol"

[[session]]
name = "media"
path = "/run/media"
startup_command = "yazi"
