#!/usr/bin/env bash
#
# A rofi powered menu to prompt for tldr documentation.
# Uses: tldr yad rofi rofi-prompt

theme="launcher_colorful_style5"
dir="$HOME/.config/rofi"

topics=$(tldr --list)

chosen=$(echo -e $topics | sed 's/, /\n/g' \
    | dmenu -p 'tldr'
)

# chosen=$(echo -n $themes \
#     | rofi -dmenu \
#            -sep ',' \
#            -p '󰞋' \
#            -l 10 \
#            -no-custom \
#            -i \
#            -theme $dir/"$theme")

if [[ $chosen == "" ]]; then
  exit 1
fi

tldr $chosen | yad --text-info \
    --center \
    --geometry=800x600 \
    --button=yad-close:1 \
    --title "tldr"
