#!/usr/bin/env bash
#
# A rofi powered menu to execute display related action.
# Uses: flavours base16 rofi rofi-prompt

theme="launcher_colorful_style5"
dir="$HOME/.config/rofi"

themes=$(flavours list)

chosen=$(echo -e $themes | sed 's/ /\n/g' \
    | dmenu -p 'theme'
)

# chosen=$(echo -n $themes \
#     | rofi -dmenu \
#            -sep ' ' \
#            -p '󰢵' \
#            -l 10 \
#            -no-custom \
#            -i \
#            -theme $dir/"$theme")

if [[ $chosen == "" ]]; then
  exit 1
fi

flavours apply $chosen && xrdb -merge ~/.Xresources

ps cax | grep xmonad > /dev/null
if [ $? -eq 0 ]; then
  xmonad --restart
fi

ps cax | grep awesome > /dev/null
if [ $? -eq 0 ]; then
  awesome-client 'awesome.restart()'
fi

ps cax | grep kitty > /dev/null
if [ $? -eq 0 ]; then
  for socket in $(ls /tmp/mykitty*); do kitty @ --to unix:$socket set-colors --all ~/.config/kitty/themes/base16-$chosen-256.conf; done
fi
