#!/usr/bin/env sh
#
# A rofi powered menu to execute display related action.
# Uses: mons autorandr rofi rofi-prompt

autodetect=' Auto-detect'
single='󰍹 Single display (primary)'
extend_to_top='󰜹 Extend to top'
extend_to_right='󰜶 Extend to right'
mirror='󰍺 Mirror'

theme="launcher_colorful_style5"
dir="$HOME/.config/rofi"

chosen=$(printf '%s;%s;%s;%s;%s\n' "$autodetect" "$single" "$extend_to_top" "$extend_to_right" \
                                   "$mirror" \
    | rofi -dmenu \
           -sep ';' \
           -p '󰍹' \
           -l 5 \
           -no-custom \
           -i \
           -theme $dir/"$theme" \
           -selected-row 1)

case "$chosen" in
    "$autodetect")
        autorandr --change --default default
        ;;

    "$single")
        mons -o
        ;;

    "$extend_to_top")
        mons -e top
        ;;

    "$extend_to_right")
        mons -e right
        ;;

    "$mirror")
        mons -m
        ;;

    *) exit 1 ;;
esac
