[[mgr.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --interactive --block'
desc = "Open shell here"

[[mgr.prepend_keymap]]
on   = ["g", "r"]
run  = "cd /"
desc = "Cd to /"

[[mgr.prepend_keymap]]
on   = ["g", "f"]
run  = "cd ~/.config"
desc = "Cd to ~/.config"

[[mgr.prepend_keymap]]
on   = ["g", "d"]
run  = "cd ~/Downloads"
desc = "Cd to ~/Downloads"

[[mgr.prepend_keymap]]
on   = ["g", "D"]
run  = "cd ~/Documents"
desc = "Cd to ~/Documents"

[[mgr.prepend_keymap]]
on   = ["g", "B"]
run  = "cd ~/Documents/Obsidian/Second\\ Brain/"
desc = "Cd to ~/Documents"

[[mgr.prepend_keymap]]
on   = ["g", "P"]
run  = "cd ~/Pictures"
desc = "Cd to ~/Pictures"

[[mgr.prepend_keymap]]
on   = ["g", "W"]
run  = "cd ~/Pictures/Wallpapers"
desc = "Cd to ~/Pictures/Wallpapers"

[[mgr.prepend_keymap]]
on   = ["g", "w"]
run  = "cd ~/code/work"
desc = "Cd to ~/code/work"

[[mgr.prepend_keymap]]
on   = ["g", "G"]
run  = "cd ~/code/work/git"
desc = "Cd to ~/code/work/git"

[[mgr.prepend_keymap]]
on   = ["g", "p"]
run  = "cd ~/code/playground"
desc = "Cd to ~/code/playground"

[[mgr.prepend_keymap]]
on   = ["g", "H"]
run  = "cd ~/code/hobby"
desc = "Cd to ~/code/hobby"

[[mgr.prepend_keymap]]
on   = ["g", "."]
run  = "cd ~/code/hobby/dotfiles"
desc = "Cd to ~/code/hobby/dotfiles"

[[mgr.prepend_keymap]]
on   = ["g", "T"]
run  = "cd ~/code/thirdparty"
desc = "Cd to ~/code/thirdparty"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin max-preview"
desc = "Maximize or restore preview"

[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "f"
run  = "plugin jump-to-char"
desc = "Jump to char"
