
[greenclip]
  blacklisted_applications = ["1password"]
  enable_image_support = false
  history_file = "/home/jnsbl/.cache/greenclip.history"
  image_cache_directory = "/tmp/greenclip"
  max_history_length = 100
  max_selection_size_bytes = 0
  static_history = ["nestingLevel=\"inline\""]
  trim_space_from_selection = true
  use_primary_selection_as_input = true
