shell = "bash -c '{}'"

[[item]]
file = "~/.config/nvim/lua/base16-colors.lua"
template = "neovim"
rewrite = true
hook = "~/.local/bin/reloadnvim"

[[item]]
file = "~/.config/kitty/base16.conf"
template = "kitty"
subtemplate = "default-256"
rewrite = true
hook = "touch ~/.config/kitty/kitty.conf"

[[item]]
file = "~/.config/alacritty/alacritty.yml"
template = "alacritty"
subtemplate = "default-256"
start = "# color_start"
end = "# color_end"

[[item]]
file = "~/.Xresources.d/base16"
template = "xresources"
subtemplate = "default-256"
hook = "xrdb -merge ~/.Xresources; awesome-client 'awesome.restart()'; xmonad --restart"
light = false
start = "! Start flavours"
end = "! End flavours"

[[item]]
file = "~/.base16_theme"
template = "shell"
rewrite = true

[[item]]
file = "~/.config/rofi/base16_colors.rasi"
template = "rofi"
subtemplate = "colors"
rewrite = true

[[item]]
file = "~/.config/fish/conf.d/base16-fzf.fish"
template = "fzf"
subtemplate = "fish"
rewrite = true

[[item]]
file = "~/.config/polybar/base16_colors.ini"
template = "polybar"
rewrite = true

[[item]]
file = "~/.config/highlight/base16_colors.theme"
template = "highlight"
rewrite = true

[[item]]
file = "~/.config/dunst/dunstrc"
template = "dunst"
subtemplate = "default"
start = "# Start flavours"
end = "# End flavours"
