-- vim.cmd('colorscheme base16-material-palenight')
require("base16-colors")
-- local base16 = require("base16")
-- base16(base16.themes.onedark, true)
-- base16(base16.themes[vim.env.BASE16_THEME or "onedark"], true)
