[mgr]
ratio          = [ 1, 3, 3 ]
linemode       = "size"

[opener]
edit = [
	{ run = 'nvim "$@"', desc = "nvim", block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$1"',                desc = "Open", for = "linux" },
]
reveal = [
	{ run = 'xdg-open "$(dirname "$1")"',           desc = "Reveal", for = "linux" },
	{ run = '''clear; exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
	{ run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
]
play = [
	{ run = 'xdg-open "$1"',                desc = "Play", for = "linux" },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]
